package:
  name: ml-codes
  version: 0.1.0

source:
  path: ..

build:
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python ==3.10.6
    - pip
  run:
    - python ==3.10.6
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - python-dotenv
    - tqdm

test:
  imports:
    - ml_codes

about:
  summary: "Machine learning utilities and experiments"
  license: MIT
